{
//=========Macro generated from canvas: cnv/cnv
//=========  (Tue Oct 25 12:21:52 2016) by ROOT version5.32/04
   TCanvas *cnv = new TCanvas("cnv", "cnv",1,1,904,904);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   cnv->SetHighLightColor(2);
   cnv->Range(-4.2,-0.26,20.8,1.74);
   cnv->SetFillColor(0);
   cnv->SetBorderMode(0);
   cnv->SetBorderSize(2);
   cnv->SetTickx(1);
   cnv->SetTicky(1);
   cnv->SetLeftMargin(0.17);
   cnv->SetRightMargin(0.03);
   cnv->SetTopMargin(0.07);
   cnv->SetBottomMargin(0.13);
   cnv->SetFrameFillStyle(0);
   cnv->SetFrameBorderMode(0);
   cnv->SetFrameFillStyle(0);
   cnv->SetFrameBorderMode(0);
   
   TH1F *h_n1_1_M_dummy = new TH1F("h_n1_1_M_dummy","h_n1_1_M_dummy",200,0.05,20.05);
   h_n1_1_M_dummy->SetMaximum(1.6);
   h_n1_1_M_dummy->SetLineStyle(0);
   h_n1_1_M_dummy->SetMarkerStyle(20);
   h_n1_1_M_dummy->GetXaxis()->SetTitle("Mass of n_{1} [GeV]");
   h_n1_1_M_dummy->GetXaxis()->SetLabelFont(42);
   h_n1_1_M_dummy->GetXaxis()->SetLabelOffset(0.007);
   h_n1_1_M_dummy->GetXaxis()->SetTitleSize(0.06);
   h_n1_1_M_dummy->GetXaxis()->SetTitleOffset(0.95);
   h_n1_1_M_dummy->GetXaxis()->SetTitleFont(42);
   h_n1_1_M_dummy->GetYaxis()->SetTitle("Fraction of events / 0.1 GeV");
   h_n1_1_M_dummy->GetYaxis()->SetLabelFont(42);
   h_n1_1_M_dummy->GetYaxis()->SetLabelOffset(0.007);
   h_n1_1_M_dummy->GetYaxis()->SetTitleSize(0.06);
   h_n1_1_M_dummy->GetYaxis()->SetTitleOffset(1.35);
   h_n1_1_M_dummy->GetYaxis()->SetTitleFont(42);
   h_n1_1_M_dummy->GetZaxis()->SetLabelFont(42);
   h_n1_1_M_dummy->GetZaxis()->SetLabelOffset(0.007);
   h_n1_1_M_dummy->GetZaxis()->SetTitleSize(0.06);
   h_n1_1_M_dummy->GetZaxis()->SetTitleFont(42);
   h_n1_1_M_dummy->Draw("");
   
   TLegend *leg = new TLegend(0.4566667,0.82,0.7822222,0.9066667,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.02777778);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL","#splitline{pp #rightarrow h #rightarrow 2n_{1} #rightarrow 2n_{D} + 2 #gamma_{D} #rightarrow 2n_{D} + 4#mu}{#splitline{m_{h} = 125 GeV, m_{n_{1}} = 10 GeV, m_{n_{D}} = 1 GeV}{m_{#gamma_{D}} = 20 GeV, c#tau_{#gamma_{D}} = 0 mm}}","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.17,0.935,0.97,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(22);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("NULL","CMS Simulation (LHE) 14TeV TeV","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   cnv->Modified();
   cnv->cd();
   cnv->SetSelected(cnv);
}
