{
//=========Macro generated from canvas: cnv/cnv
//=========  (Tue Oct 25 13:28:03 2016) by ROOT version5.32/04
   TCanvas *cnv = new TCanvas("cnv", "cnv",1,1,904,904);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   cnv->SetHighLightColor(2);
   cnv->Range(-1062.5,-0.00585,5187.5,0.03915);
   cnv->SetFillColor(0);
   cnv->SetBorderMode(0);
   cnv->SetBorderSize(2);
   cnv->SetTickx(1);
   cnv->SetTicky(1);
   cnv->SetLeftMargin(0.17);
   cnv->SetRightMargin(0.03);
   cnv->SetTopMargin(0.07);
   cnv->SetBottomMargin(0.13);
   cnv->SetFrameFillStyle(0);
   cnv->SetFrameBorderMode(0);
   cnv->SetFrameFillStyle(0);
   cnv->SetFrameBorderMode(0);
   
   TH1F *h_gammaD_cT_dummy = new TH1F("h_gammaD_cT_dummy","h_gammaD_cT_dummy",100,0,5000);
   h_gammaD_cT_dummy->SetMaximum(0.036);
   h_gammaD_cT_dummy->SetLineStyle(0);
   h_gammaD_cT_dummy->SetMarkerStyle(20);
   h_gammaD_cT_dummy->GetXaxis()->SetTitle("c#tau of #gamma_{D} [mm]");
   h_gammaD_cT_dummy->GetXaxis()->SetLabelFont(42);
   h_gammaD_cT_dummy->GetXaxis()->SetLabelOffset(0.007);
   h_gammaD_cT_dummy->GetXaxis()->SetTitleSize(0.06);
   h_gammaD_cT_dummy->GetXaxis()->SetTitleOffset(0.95);
   h_gammaD_cT_dummy->GetXaxis()->SetTitleFont(42);
   h_gammaD_cT_dummy->GetYaxis()->SetTitle("Normalized Fraction of Events / 50.0 mm");
   h_gammaD_cT_dummy->GetYaxis()->SetLabelFont(42);
   h_gammaD_cT_dummy->GetYaxis()->SetLabelOffset(0.007);
   h_gammaD_cT_dummy->GetYaxis()->SetTitleSize(0.05);
   h_gammaD_cT_dummy->GetYaxis()->SetTitleOffset(1.3);
   h_gammaD_cT_dummy->GetYaxis()->SetTitleFont(42);
   h_gammaD_cT_dummy->GetZaxis()->SetLabelFont(42);
   h_gammaD_cT_dummy->GetZaxis()->SetLabelOffset(0.007);
   h_gammaD_cT_dummy->GetZaxis()->SetTitleSize(0.06);
   h_gammaD_cT_dummy->GetZaxis()->SetTitleFont(42);
   h_gammaD_cT_dummy->Draw("");
   
   TH1F *h_gammaD_cT = new TH1F("h_gammaD_cT","h_gammaD_cT",100,0,5000);
   h_gammaD_cT->SetBinContent(1,0.02);
   h_gammaD_cT->SetEntries(99998);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#0000ff");
   h_gammaD_cT->SetLineColor(ci);
   h_gammaD_cT->SetLineWidth(2);
   h_gammaD_cT->SetMarkerStyle(20);
   h_gammaD_cT->GetXaxis()->SetTitle("c#tau of #gamma_{D} [mm]");
   h_gammaD_cT->GetXaxis()->SetLabelFont(42);
   h_gammaD_cT->GetXaxis()->SetLabelOffset(0.007);
   h_gammaD_cT->GetXaxis()->SetTitleSize(0.06);
   h_gammaD_cT->GetXaxis()->SetTitleOffset(0.95);
   h_gammaD_cT->GetXaxis()->SetTitleFont(42);
   h_gammaD_cT->GetYaxis()->SetTitle("Normalized Fraction of events");
   h_gammaD_cT->GetYaxis()->SetLabelFont(42);
   h_gammaD_cT->GetYaxis()->SetLabelOffset(0.007);
   h_gammaD_cT->GetYaxis()->SetTitleSize(0.05);
   h_gammaD_cT->GetYaxis()->SetTitleOffset(1.5);
   h_gammaD_cT->GetYaxis()->SetTitleFont(42);
   h_gammaD_cT->GetZaxis()->SetLabelFont(42);
   h_gammaD_cT->GetZaxis()->SetLabelOffset(0.007);
   h_gammaD_cT->GetZaxis()->SetTitleSize(0.06);
   h_gammaD_cT->GetZaxis()->SetTitleFont(42);
   h_gammaD_cT->Draw("same");
   
   TF1 *funct = new TF1("funct","exp(-x/1000)/(1000*(1-exp(-5000.0/1000)))",0,5000);
   funct->SetNpx(10000);
   funct->SetFillColor(19);
   funct->SetFillStyle(0);
   funct->SetMarkerStyle(20);
   funct->SetLineColor(2);
   funct->SetLineWidth(1);
   funct->GetXaxis()->SetLabelFont(42);
   funct->GetXaxis()->SetLabelOffset(0.007);
   funct->GetXaxis()->SetTitleSize(0.06);
   funct->GetXaxis()->SetTitleOffset(0.95);
   funct->GetXaxis()->SetTitleFont(42);
   funct->GetYaxis()->SetLabelFont(42);
   funct->GetYaxis()->SetLabelOffset(0.007);
   funct->GetYaxis()->SetTitleSize(0.06);
   funct->GetYaxis()->SetTitleOffset(1.3);
   funct->GetYaxis()->SetTitleFont(42);
   funct->Draw("same");
   
   TLegend *leg = new TLegend(0.4566667,0.82,0.7822222,0.9066667,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.02777778);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL","#splitline{pp #rightarrow h #rightarrow 2n_{1} #rightarrow 2n_{D} + 2 #gamma_{D} #rightarrow 2n_{D} + 4#mu}{#splitline{m_{h} = 125 GeV, m_{n_{1}} = 10 GeV, m_{n_{D}} = 1 GeV}{m_{#gamma_{D}} = 20 GeV, c#tau_{#gamma_{D}} = 1000 mm}}","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.17,0.935,0.97,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(22);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("NULL","CMS Simulation (LHE) 14TeV TeV","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.46,0.6744444,0.6955556,0.7644444,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.02777778);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("funct","#frac{e^{-x/1000}}{1000 (1 - e^{-5000.0/1000})}","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   cnv->Modified();
   cnv->cd();
   cnv->SetSelected(cnv);
}
