{
//=========Macro generated from canvas: cnv/cnv
//=========  (Tue Oct 25 15:28:15 2016) by ROOT version5.32/04
   TCanvas *cnv = new TCanvas("cnv", "cnv",1,1,904,904);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   cnv->SetHighLightColor(2);
   cnv->Range(-2.125,-0.17875,10.375,1.19625);
   cnv->SetFillColor(0);
   cnv->SetBorderMode(0);
   cnv->SetBorderSize(2);
   cnv->SetTickx(1);
   cnv->SetTicky(1);
   cnv->SetLeftMargin(0.17);
   cnv->SetRightMargin(0.03);
   cnv->SetTopMargin(0.07);
   cnv->SetBottomMargin(0.13);
   cnv->SetFrameFillStyle(0);
   cnv->SetFrameBorderMode(0);
   cnv->SetFrameFillStyle(0);
   cnv->SetFrameBorderMode(0);
   
   TH1F *h_higgs_pT_dummy = new TH1F("h_higgs_pT_dummy","h_higgs_pT_dummy",10,0,10);
   h_higgs_pT_dummy->SetMaximum(1.1);
   h_higgs_pT_dummy->SetLineStyle(0);
   h_higgs_pT_dummy->SetMarkerStyle(20);
   h_higgs_pT_dummy->GetXaxis()->SetTitle("p_{T} of h [GeV]");
   h_higgs_pT_dummy->GetXaxis()->SetLabelFont(42);
   h_higgs_pT_dummy->GetXaxis()->SetLabelOffset(0.007);
   h_higgs_pT_dummy->GetXaxis()->SetTitleSize(0.06);
   h_higgs_pT_dummy->GetXaxis()->SetTitleOffset(0.95);
   h_higgs_pT_dummy->GetXaxis()->SetTitleFont(42);
   h_higgs_pT_dummy->GetYaxis()->SetTitle("Fraction of events / 1 GeV");
   h_higgs_pT_dummy->GetYaxis()->SetLabelFont(42);
   h_higgs_pT_dummy->GetYaxis()->SetLabelOffset(0.007);
   h_higgs_pT_dummy->GetYaxis()->SetTitleSize(0.06);
   h_higgs_pT_dummy->GetYaxis()->SetTitleOffset(1.35);
   h_higgs_pT_dummy->GetYaxis()->SetTitleFont(42);
   h_higgs_pT_dummy->GetZaxis()->SetLabelFont(42);
   h_higgs_pT_dummy->GetZaxis()->SetLabelOffset(0.007);
   h_higgs_pT_dummy->GetZaxis()->SetTitleSize(0.06);
   h_higgs_pT_dummy->GetZaxis()->SetTitleFont(42);
   h_higgs_pT_dummy->Draw("");
   
   TH1F *h_higgs_pT__2 = new TH1F("h_higgs_pT__2","h_higgs_pT",10,0,10);
   h_higgs_pT__2->SetBinContent(1,1);
   h_higgs_pT__2->SetEntries(49999);
   h_higgs_pT__2->SetDirectory(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#0000ff");
   h_higgs_pT__2->SetLineColor(ci);
   h_higgs_pT__2->SetLineWidth(2);
   h_higgs_pT__2->SetMarkerStyle(20);
   h_higgs_pT__2->GetXaxis()->SetLabelFont(42);
   h_higgs_pT__2->GetXaxis()->SetLabelOffset(0.007);
   h_higgs_pT__2->GetXaxis()->SetTitleSize(0.06);
   h_higgs_pT__2->GetXaxis()->SetTitleOffset(0.95);
   h_higgs_pT__2->GetXaxis()->SetTitleFont(42);
   h_higgs_pT__2->GetYaxis()->SetLabelFont(42);
   h_higgs_pT__2->GetYaxis()->SetLabelOffset(0.007);
   h_higgs_pT__2->GetYaxis()->SetTitleSize(0.06);
   h_higgs_pT__2->GetYaxis()->SetTitleOffset(1.3);
   h_higgs_pT__2->GetYaxis()->SetTitleFont(42);
   h_higgs_pT__2->GetZaxis()->SetLabelFont(42);
   h_higgs_pT__2->GetZaxis()->SetLabelOffset(0.007);
   h_higgs_pT__2->GetZaxis()->SetTitleSize(0.06);
   h_higgs_pT__2->GetZaxis()->SetTitleFont(42);
   h_higgs_pT__2->Draw("same");
   
   TLegend *leg = new TLegend(0.4566667,0.82,0.7822222,0.9066667,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.02777778);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL","#splitline{pp #rightarrow h #rightarrow 2n_{1} #rightarrow 2n_{D} + 2 #gamma_{D} #rightarrow 2n_{D} + 4#mu}{#splitline{m_{h} = 125 GeV, m_{n_{1}} = 10 GeV, m_{n_{D}} = 1 GeV}{m_{#gamma_{D}} = 20 GeV, c#tau_{#gamma_{D}} = 1000 mm}}","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.17,0.935,0.97,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(22);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("NULL","CMS Simulation (LHE) 14TeV TeV","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   cnv->Modified();
   cnv->cd();
   cnv->SetSelected(cnv);
}
