{
//=========Macro generated from canvas: cnv/cnv
//=========  (Tue Oct 25 16:11:56 2016) by ROOT version5.32/04
   TCanvas *cnv = new TCanvas("cnv", "cnv",1,1,904,904);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   cnv->SetHighLightColor(2);
   cnv->Range(0.9035443,-17875,1.496351,119625);
   cnv->SetFillColor(0);
   cnv->SetBorderMode(0);
   cnv->SetBorderSize(2);
   cnv->SetLogx();
   cnv->SetTickx(1);
   cnv->SetTicky(1);
   cnv->SetLeftMargin(0.17);
   cnv->SetRightMargin(0.03);
   cnv->SetTopMargin(0.07);
   cnv->SetBottomMargin(0.13);
   cnv->SetFrameFillStyle(0);
   cnv->SetFrameBorderMode(0);
   cnv->SetFrameFillStyle(0);
   cnv->SetFrameBorderMode(0);
   
   TH1F *h_m2 = new TH1F("h_m2","h_m2",101,10.1,30.1);
   h_m2->SetBinContent(50,49999);
   h_m2->SetMaximum(110000);
   h_m2->SetEntries(49999);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#0000ff");
   h_m2->SetLineColor(ci);
   h_m2->SetLineWidth(2);
   h_m2->SetMarkerStyle(20);
   h_m2->GetXaxis()->SetTitle("m_{#mu#mu} [GeV]");
   h_m2->GetXaxis()->SetLabelFont(42);
   h_m2->GetXaxis()->SetLabelOffset(0.007);
   h_m2->GetXaxis()->SetTitleSize(0.06);
   h_m2->GetXaxis()->SetTitleOffset(0.95);
   h_m2->GetXaxis()->SetTitleFont(42);
   h_m2->GetYaxis()->SetTitle("Events / 0.1 GeV");
   h_m2->GetYaxis()->SetLabelFont(42);
   h_m2->GetYaxis()->SetLabelOffset(0.007);
   h_m2->GetYaxis()->SetTitleSize(0.06);
   h_m2->GetYaxis()->SetTitleOffset(1.35);
   h_m2->GetYaxis()->SetTitleFont(42);
   h_m2->GetZaxis()->SetLabelFont(42);
   h_m2->GetZaxis()->SetLabelOffset(0.007);
   h_m2->GetZaxis()->SetTitleSize(0.06);
   h_m2->GetZaxis()->SetTitleFont(42);
   h_m2->Draw("");
   
   TH1F *h_m1 = new TH1F("h_m1","h_m1",101,0.1,10.1);
   h_m1->SetBinContent(102,49999);
   h_m1->SetEntries(49999);

   ci = TColor::GetColor("#ff0000");
   h_m1->SetLineColor(ci);
   h_m1->SetLineWidth(2);
   h_m1->SetMarkerStyle(20);
   h_m1->GetXaxis()->SetLabelFont(42);
   h_m1->GetXaxis()->SetLabelOffset(0.007);
   h_m1->GetXaxis()->SetTitleSize(0.06);
   h_m1->GetXaxis()->SetTitleOffset(0.95);
   h_m1->GetXaxis()->SetTitleFont(42);
   h_m1->GetYaxis()->SetLabelFont(42);
   h_m1->GetYaxis()->SetLabelOffset(0.007);
   h_m1->GetYaxis()->SetTitleSize(0.06);
   h_m1->GetYaxis()->SetTitleOffset(1.3);
   h_m1->GetYaxis()->SetTitleFont(42);
   h_m1->GetZaxis()->SetLabelFont(42);
   h_m1->GetZaxis()->SetLabelOffset(0.007);
   h_m1->GetZaxis()->SetTitleSize(0.06);
   h_m1->GetZaxis()->SetTitleFont(42);
   h_m1->Draw("same");
   
   TLegend *leg = new TLegend(0.4566667,0.82,0.7822222,0.9066667,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.02777778);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL","#splitline{pp #rightarrow h #rightarrow 2n_{1} #rightarrow 2n_{D} + 2 #gamma_{D} #rightarrow 2n_{D} + 4#mu}{#splitline{m_{h} = 125 GeV, m_{n_{1}} = 10 GeV, m_{n_{D}} = 1 GeV}{m_{#gamma_{D}} = 20 GeV, c#tau_{#gamma_{D}} = 100 mm}}","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.17,0.935,0.97,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(22);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("NULL","CMS Simulation (LHE) 14TeV TeV","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.17,0.935,0.97,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(22);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("NULL","CMS Simulation (LHE) 14TeV TeV","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   cnv->Modified();
   cnv->cd();
   cnv->SetSelected(cnv);
}
